# Generated by Django 3.2.17 on 2023-02-12 19:21

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0062_rename_configcontext_role"),
        ("nautobot_bgp_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peergroup",
            name="role_new",
            field=nautobot.extras.models.roles.RoleField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_bgp_models_peergroup_related",
                to="extras.role",
            ),
        ),
        migrations.AddField(
            model_name="peergrouptemplate",
            name="role_new",
            field=nautobot.extras.models.roles.RoleField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_bgp_models_peergrouptemplate_related",
                to="extras.role",
            ),
        ),
        migrations.AddField(
            model_name="peerendpoint",
            name="role_new",
            field=nautobot.extras.models.roles.RoleField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nautobot_bgp_models_peerendpoint_related",
                to="extras.role",
            ),
        ),
    ]
