# Generated by Django 3.2.18 on 2023-03-15 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_bgp_models", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="peergroup",
            old_name="template",
            new_name="peergroup_template",
        ),
    ]
