# Generated by Django 3.1.8 on 2021-06-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0003_remove_max_length"),
        ("nautobot_bgp_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peerendpoint",
            options={"ordering": ["local_ip"], "verbose_name": "BGP peer endpoint"},
        ),
        migrations.RenameField(
            model_name="peerendpoint",
            old_name="send_community",
            new_name="send_community_ebgp",
        ),
        migrations.RenameField(
            model_name="peergroup",
            old_name="send_community",
            new_name="send_community_ebgp",
        ),
        migrations.RemoveField(
            model_name="peerendpoint",
            name="device_content_type",
        ),
        migrations.RemoveField(
            model_name="peerendpoint",
            name="device_object_id",
        ),
        migrations.RemoveField(
            model_name="peerendpoint",
            name="export_policy",
        ),
        migrations.RemoveField(
            model_name="peerendpoint",
            name="import_policy",
        ),
        migrations.RemoveField(
            model_name="peerendpoint",
            name="multipath",
        ),
        migrations.RemoveField(
            model_name="peergroup",
            name="export_policy",
        ),
        migrations.RemoveField(
            model_name="peergroup",
            name="import_policy",
        ),
        migrations.RemoveField(
            model_name="peergroup",
            name="multipath",
        ),
        migrations.AddField(
            model_name="addressfamily",
            name="maximum_prefix",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="addressfamily",
            name="multipath",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peerendpoint",
            name="peer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_bgp_models.peerendpoint",
            ),
        ),
        migrations.AddField(
            model_name="peerendpoint",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endpoints",
                to="nautobot_bgp_models.peersession",
            ),
        ),
        migrations.AddField(
            model_name="peersession",
            name="authentication_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="peerendpoint",
            name="local_ip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bgp_peer_endpoints", to="ipam.ipaddress"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="peersession",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="peersession",
            name="_authentication_key",
        ),
        migrations.RemoveField(
            model_name="peersession",
            name="endpoint_a",
        ),
        migrations.RemoveField(
            model_name="peersession",
            name="endpoint_z",
        ),
    ]
