# Generated by Django 3.1.13 on 2021-09-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_bgp_models", "0004_auto_20210831_1834"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peergroup",
            options={"ordering": ["name"], "verbose_name": "BGP peer group"},
        ),
        migrations.AlterUniqueTogether(
            name="addressfamily",
            unique_together={("afi_safi", "peer_group", "peer_endpoint")},
        ),
        migrations.AlterUniqueTogether(
            name="peergroup",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="addressfamily",
            name="device_content_type",
        ),
        migrations.RemoveField(
            model_name="addressfamily",
            name="device_object_id",
        ),
        migrations.RemoveField(
            model_name="peergroup",
            name="device_content_type",
        ),
        migrations.RemoveField(
            model_name="peergroup",
            name="device_object_id",
        ),
    ]
