# Generated by Django 3.2.17 on 2023-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_bgp_models", "0004_use_upstream_role_part3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="peergroup",
            old_name="role_new",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="peergrouptemplate",
            old_name="role_new",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="peerendpoint",
            old_name="role_new",
            new_name="role",
        ),
    ]
