# Generated by Django 4.2.19 on 2025-05-20 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0062_module_data_migration"),
        ("ipam", "0047_alter_ipaddress_role_alter_ipaddress_status_and_more"),
        ("nautobot_bgp_models", "0010_alter_autonomoussystem_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bgproutinginstance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bgproutinginstance",
            name="vrf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bgp_routing_instances",
                to="ipam.vrf",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bgproutinginstance",
            unique_together={("device", "autonomous_system", "vrf")},
        ),
    ]
