# Generated by Django 4.2.17 on 2025-02-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_update_all_charfields_max_length_to_255'),
        ('nautobot_bgp_models', '0010_alter_autonomoussystem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomoussystem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
    ]
