# Generated by Django 3.2.24 on 2024-07-04 06:43

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.roles
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0046_update_all_charfields_max_length_to_255'),
        ('extras', '0108_jobbutton_enabled'),
        ('dcim', '0058_controller_data_migration'),
        ('nautobot_bgp_models', '0010_auto_20240704_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerGroupTemplateEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('extra_attributes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('autonomous_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_group_template_endpoints', to='nautobot_bgp_models.autonomoussystem')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nautobot_bgp_models.peergrouptemplateendpoint')),
                ('peer_group_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_group_template_endpoints', to='nautobot_bgp_models.peergrouptemplate')),
                ('role', nautobot.extras.models.roles.RoleField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_peer_group_template_endpoints', to='extras.role')),
                ('routing_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bgp_group_template_endpoints', to='nautobot_bgp_models.bgproutinginstance')),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_group_template_endpoints', to='extras.secret')),
                ('source_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_group_template_endpoints', to='dcim.interface')),
                ('source_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_group_template_endpoints', to='ipam.ipaddress')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BGP Peer Group Template Endpoint',
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
