# Generated by Django 4.2.19 on 2025-02-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_update_all_charfields_max_length_to_255'),
        ('nautobot_bgp_models', '0011_autonomoussystem_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomoussystem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autonomous_systems', to='tenancy.tenant'),
        ),
    ]
