# Generated by Django 3.2.24 on 2024-07-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_bgp_models', '0011_peergrouptemplateendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peergrouptemplateendpoint',
            name='peer_group_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='nautobot_bgp_models.peergrouptemplate'),
        ),
    ]
